service: employee-portal
provider:
  name: aws
  runtime: nodejs18.x
  stage: sit
  region: ap-south-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.postsTableName}
custom:
  postsTableName: Employee_Table
plugins:
  - serverless-iam-roles-per-function
functions:
  deleteEmployee:
    handler:  Lib/DeleteModule/api.handleDeleteOperation
    name: Delete-Employee
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: employees/{empId}
          method: DELETE
      - http:
          path: PATCH /employees/{empId}   
          method: DELETE # Change the method to PATCH     
    iamRoleStatements:
      - Effect: "Allow"
        Action:
        - "dynamodb:DeleteItem"
        - "dynamodb:UpdateItem"
        Resource: !GetAtt PostsTable.Arn # The resource remains the same   
  performanceHandler:
    handler:  Lib/PerformanceModule/api.performanceHandler
    name: Performance-Handler
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: performance/create/{empId}
          method: POST
      - http:
          path: performance/update/{empId}
          method: PUT    
    iamRoleStatements:
      - Effect: "Allow"
        Action:
        - "dynamodb:CreateItem"
        - "dynamodb:UpdateItem"
        Resource: !GetAtt PostsTable.Arn # The resource remains the same         
resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.postsTableName}
        AttributeDefinitions:
          - AttributeName: empId
            AttributeType: S
        KeySchema:
          - AttributeName: empId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1